name: Publish to GitHub Package Registry

on:
  push:
    branches: [ main]
      
workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install package dependencies
      run: npm install

    - name: Build your package or artifact
      run: npm run build  # Modify this step to build your specific package or artifact

    - name: Publish to GitHub Package Registry
      run: npm publish --access public  # Modify this step based on your package manager (e.g., npm, NuGet, etc.)
      env:
        NODE_AUTH_TOKEN: ${{secrets.TEST_SECRET}}
